GET http://localhost:3000/


### Register =========================================================================================
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "username": "hermione",
  "email": "hermionegranger@email.com",
  "password": "secret123",
  "image": "https://placeimg.com/100/100/people"
}


### Login ============================================================================================
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "hermionegranger@email.com",
  "password": "secret123"
}


### Questions ========================================================================================
GET http://localhost:3000/api/questions


### ----------------------------------
POST http://localhost:3000/api/questions
Content-Type: application/json

{
  "userId": 9,
  "title": "test title",
  "content": "test content"
}


### ----------------------------------
PUT http://localhost:3000/api/questions/10
Content-Type: application/json

{
  "title": "update question title",
  "content": "update question content"
}


### ----------------------------------
DELETE http://localhost:3000/api/questions/10


### Answers ========================================================================================
GET http://localhost:3000/api/answers


### ----------------------------------
POST http://localhost:3000/api/answers
Content-Type: application/json

{
  "userId": 9,
  "questionId": 1,
  "content": "test content"
}


### ----------------------------------
PATCH http://localhost:3000/api/answers/10
Content-Type: application/json

{
  "content": "update answer content"
}


### ----------------------------------
DELETE http://localhost:3000/api/answers/10
