GET http://localhost:3000/


### Register =========================================================================================
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "username": "hermione",
  "email": "hermionegranger@email.com",
  "password": "secret123",
  "passwordConfirm": "secret123",  
  "image": "https://placeimg.com/100/100/people"
}


### Login ============================================================================================
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "hermionegranger@email.com",
  "password": "secret123"
}


### Questions ========================================================================================
GET http://localhost:3000/api/questions


### ----------------------------------
GET http://localhost:3000/api/questions/1


### ----------------------------------
POST http://localhost:3000/api/questions
Content-Type: application/json
Authorization: Bearer ...

{
  "title": "test title",
  "content": "test content"
}


### ----------------------------------
PUT http://localhost:3000/api/questions/10
Content-Type: application/json
Authorization: Bearer ...

{
  "title": "update question title",
  "content": "update question content"
}


### ----------------------------------
DELETE http://localhost:3000/api/questions/10
Content-Type: application/json
Authorization: Bearer ...


### Answers ========================================================================================
### ---------------------------------- with token
GET http://localhost:3000/api/questions/1/answers
Content-Type: application/json
Authorization: Bearer ...


### ---------------------------------- without token


GET http://localhost:3000/api/questions/1/answers


### ----------------------------------
POST http://localhost:3000/api/questions/4/answers
Content-Type: application/json
Authorization: Bearer ...

{
  "content": "test content"
}


### ----------------------------------
PATCH http://localhost:3000/api/answers/10
Content-Type: application/json
Authorization: Bearer ...

{
  "content": "update answer content"
}


### ----------------------------------
DELETE http://localhost:3000/api/answers/10
Content-Type: application/json
Authorization: Bearer ...


### Votes ========================================================================================
### Check if the user has already voted this answer -----
GET http://localhost:3000/api/answers/2/vote
Content-Type: application/json
Authorization: Bearer ...


### Post answer vote ----------------------------------
POST http://localhost:3000/api/answers/2/vote
Content-Type: application/json
Authorization: Bearer ...

{
  "vote": 1
}


### Patch answer vote ----------------------------------
PATCH http://localhost:3000/api/answers/2/vote
Content-Type: application/json
Authorization: Bearer ...

{
  "vote": -1
}


### Delete answer vote ---------------------------------
DELETE http://localhost:3000/api/answers/22/vote
Content-Type: application/json
Authorization: Bearer ...
